### ISSUE TITLE
WLED Segment control goes here!

### ISSUE THREAD

**Issue by sergge1** [swinbkh/Ambilight2WLED#2]
Deart @swinbkh 
could you please advise me, should I add something here into the code while using usermod for WLED? 

[WLED Segment control goes here!](https://github.com/swinbkh/Ambilight2WLED/blob/888d47cf84cff69dbe6f7eb51aeac740ee89bc79/Ambilight_to_WLED_Usermod.h#L96-L98)

**Comment by swinbkh** [comment]
Hi @sergge1 , I never managed to get this implemented as a usermod, but at the point where the code suggests "WLED Segment control goes here", is where all the other processing is done, and ready to handover to WLED to output the colours. 

If you know how to join this last bit up to get it to work as a usermod, I'd love to hear it, as I've been using the standalone variant which uses an additional esp8266.
